spring:
  application:
    name: blackjack-api

  mongodb:
    uri: mongodb://mongo-db:27017/blackjack_db
    auto-index-creation: true

  r2dbc:
    url: r2dbc:mysql://mysql-db:3306/blackjack_db
    username: root
    password: root
    pool:
      initial-size: 10
      max-size: 20

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true